### ISSUE TITLE
Remove and rename some columns

### ISSUE THREAD

**Issue by FlorianWilhelm** [inovex/justcause-data#3]
Currently, the IBM dataset has a size column reflecting the size of each replication. This information is superfluous since it can be also determined with a simple `groupby("rep").count()` operation. Thus we should remove it from the parquet file. 

Also rename `y_0` to `mu_0` and `y_1` to `my_1` and change accordingly in the `Col` object.

**Comment by MaximilianFranz** [comment]
Done in [fcce43a74a](https://github.com/inovex/justcause-data/commit/fcce43a74a516e43db599f2933a0c6479099c17e).
